### ISSUE TITLE
Deleting Kafka Schema won't delete on Aiven side

### ISSUE THREAD

**Issue by jonatasbaldin** [aiven/aiven-operator#116]
Steps to reproduce:

1. Create a Kafka Schema:
```yaml
apiVersion: aiven.io/v1alpha1
kind: KafkaSchema
metadata:
  name: kafka-schema
spec:
  authSecretRef:
    name: aiven-token
    key: token
  
  project: <tour-project-name>
  serviceName: kafka-sample
  subjectName: MySchema

  schema: |
    {
      "type": "record",
      "name": "MySchema",
      "fields": [
        {
          "name": "field",
          "type": "string"
        }
      ]
    }

  compatibilityLevel: BACKWARD
```

2. Delete the Kafka Schema with:
```bash
$ kubectl delete kafkaschemas.aiven.io kafka-schema
```

The command doesn't fail, but the Schema remains visible/available through the web console.
