### ISSUE TITLE
Replace `.` in fields with an actual object

### ISSUE THREAD

**Issue by xvzf** [aiven/aiven-operator#200]
We recently had this issue here: https://github.com/jsonnet-libs/k8s/pull/198

Would it make sense to rather have a nested object instead of having a `.` in the field?
E.g.:

```yaml
# ...
test:
  a: avalue
  b: bvalue
```
instead of
```yaml
# ...
test.a: avalue
test.b: bvalue
```
