### ISSUE TITLE
Exporting more PostgreSQL connection information to Secret

### ISSUE THREAD

**Issue by jonatasbaldin** [aiven/aiven-operator#46]
Hi there!

Currently we are only exporting `host`, `password`, `port` and `user` fields to the Kubernetes Secret when creating a PG resource.

I believe we could export all the fields, including a `DATABSE_URL` formatted version.

We should also respect the default [PostgreSQL environment variable names](https://www.postgresql.org/docs/9.2/libpq-envars.html):

This is how I believe the generate Secret should look like:

```yaml
apiVersion: v1
data:
  PGHOST: pg-sample-project.aivencloud.com
  PGPORT: 13039
  PGDATABASE: defaultdb
  PGUSER: avnadmin
  PGPASSWORD: password
  PGSSLMODE: require

  # a concatenated version of the values above
  DATABASE_URL: postgres://user:pass@host:port/databse?sslmode=mode
kind: Secret
metadata:
  name: pg-sample-pg-secret
type: Opaque
```

This should be applied to anything related to PostgreSQL.
