### ISSUE TITLE
RFE: Make Aiven Operator more GitOps Friendly

### ISSUE THREAD

**Issue by christianh814** [aiven/aiven-operator#472]
The Aiven Operator is great and I can deploy a DB (sample using MYSQL) using it

```yaml
apiVersion: aiven.io/v1alpha1
kind: MySQL
metadata:
  name: mysql-sample
spec:
  authSecretRef:
    name: aiven-token
    key: token
  connInfoSecretTarget:
    name: mysql-secret
  project: myproj
  cloudName: google-europe-west1
  plan: startup-4
```

However this stores the credentials in a secret. as specified under `spec.connInfoSecretTarget`

Usually (and especially true when doing GitOps with Flux/Argo CD), the secret needs to be stored in Git. More specifically it's stored in Git via Vault, Sealed Secrets, and/or External Secret Operator.

I would like to be able to set up connection parameters beforehand (or as much as I can) and have the Aiven Operator "respect" these parameters (i.e. use the parameters to set up the DB).

**Comment by byashimov** [comment]
Hey. 

> The Aiven Operator is great and I can deploy a DB (sample using MYSQL) using it

Thank you, that's very nice of you.

Would this work for you?  
Say you have applied this yaml stored in git:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: bXktc2VjcmV0

---

apiVersion: aiven.io/v1alpha1
kind: MySQL
metadata:
  name: mysql-sample
spec:
  connInfoSecretTarget:
    name: mysecret
```

1. if you provide `connInfoSecretTarget.name` pointing to an existing `Secret` then the Operator uses that creds to set
2. if no `Secret` found, it creates a new one (as it does right now)

The only thing is that we can't validate the `Secret`.
