### ISSUE TITLE
[IDEA] Another way to refer to the Project

### ISSUE THREAD

**Issue by jonatasbaldin** [aiven/aiven-operator#50]
Hey there,

As discussed in #43, we decided to not have `.Spec.projectRef` field in the Resources to refer to a Project, since it would take a lot of work.

I had an idea on injecting the Project name inside the `authSecretRef`, since it is used for authentication as well.

Something like:
```yaml
apiVersion: aiven.io/v1alpha1
kind: PG
metadata:
  name: pg-sample
spec:
  
  authSecretRef:
    # make a nested key/value structure
    authToken:
	  name: aiven-token
	  key: token

    # inform the name through a Secret (could be the same with a different key)
	projectName:
	  name: aiven-token
	  key: project_name

  connInfoSecretTarget:
    name: pg-connection

  # remove the `project` field 
  # project: <>

  # the rest is the same
  cloudName: google-europe-west1
  plan: hobbyist
  maintenanceWindowDow: friday
  maintenanceWindowTime: 23:00:00
  pgUserConfig:
    pg_version: '11'
```

What do you think @ivan-savciuc ?
