### ISSUE TITLE
Cannot create ServiceUser

### ISSUE THREAD

**Issue by jonatasbaldin** [aiven/aiven-operator#54]
Hi there,

I'm trying to create a ServiceUser using the following YAML:
```yaml
apiVersion: aiven.io/v1alpha1
kind: ServiceUser
metadata:
  name: service-user-sample
spec:
  authSecretRef:
    name: aiven-token
    key: token
  
  connInfoSecretTarget:
    name: service-user-sample

  project: dev-advocates
  serviceName: pg-sample
  # authentication: caching_sha2_password
```

But I get the following error on the controller logs:
```
2021-06-16T09:00:48.893Z ERROR controller-runtime.manager.controller.serviceuser Reconciler error {"reconciler group": "aiven.io", "reconciler kind": "ServiceUser", "name": "service-user-sample", "namespace": "default", "error": "serviceusers.aiven.io \"service-user-sample\" is forbidden: User \"system:serviceaccount:aiven-kubernetes-operator-system:default\" cannot update resource \"serviceusers\" in API group \"aiven.io\" in the namespace \"default\""}
```

I believe we need to give the controller service user more privileges :thinking_face: 

What do you think?
