### ISSUE TITLE
Implement Error Conditions

### ISSUE THREAD

**Issue by jonatasbaldin** [aiven/aiven-operator#66]
We also need to set a Condition if the instance is in an error state. For example, when creating a PG instance with `cloudName: not-a-cloud`, I got an error on the logs, but the `.Status` is all empty.

I would expect something like:
```yaml
    - lastTransitionTime: "2021-06-23T12:33:34Z"
      message: Invalid cloudName `not-a-cloud`
      reason: ErrInvalidCloud
      status: Unknown
      type: Error
```
