### ISSUE TITLE
Implement REBUILDING Conditions

### ISSUE THREAD

**Issue by jonatasbaldin** [aiven/aiven-operator#67]
While the Service is in the REBUILDING state on Aiven side we have the following Condition:
```yaml
    - lastTransitionTime: "2021-06-23T12:33:34Z"
      message: Instance was created or update on Aiven side, status remains unknown
      reason: CreatedOrUpdate
      status: Unknown
      type: Running
```

Could we implement something like this:
```yalm
    - lastTransitionTime: "2021-06-23T12:33:34Z"
      message: Instance is rebuilding on Aiven side
      reason: CreatedOrUpdate
      status: True  # set to true
      type: Rebuilding  # a new type named Rebuilding
```
