### ISSUE TITLE
Support for privatelink urls?

### ISSUE THREAD

**Issue by christoffer-eide** [aiven/aiven-operator#751]
We have enabled AWS private link for some of our kafka and postgres services. In the aiven console, we can view both the "dynamic" (regular) urls, and the private link urls.

When we create a `ServiceUser`, the generated secret contains only the dynamic/regular urls:
```yaml
apiVersion: v1
kind: Secret
data:
  HOST: <pg-service-name>-<aiven-project>.aivencloud.com
  PORT: 26586
```

This makes it cumbersome for our dev teams to use the operator, as they need to use `USENAME`, `PASSWORD` and `CA_CERT` from the generated secret and configure the `HOST` elsewhere.

Would it be possible to get the operator to use the privatelink urls (if available) in the genererated secret? 
```yaml
apiVersion: aiven.io/v1alpha1
kind: ServiceUser
spec:
  connInfoSecretTarget:
    name: generated-secret-name
    usePrivateLinkIfAvailable: true
```
