### ISSUE TITLE
serviceUser(secret): values are duplicated in different "very common" keys

### ISSUE THREAD

**Issue by 6uellerBpanda** [aiven/aiven-operator#801]
I would like to use the created `Secret` as a whole to inject it as env var:

```yaml
envFrom:
  - secretRef:
       name: aiven-service-user-secret
```

but the created `Secret` has "common" keys e.g. PASSWORD, USERNAME,... defined which would collide with other env vars:

```yaml
apiVersion: v1
data:
  PASSWORD: foo
  SERVICEUSER_PASSWORD: foo
```

I tried to use the `spec.connInfoSecretTarget.prefix` option but this applies only to the SERVICEUSER keys part.

right now we can of course workaround it with specifying the keys individually:

```yaml
- name: KAFKA_SERVICE_PASSWORD
   valueFrom:
     secretKeyRef:
       name: aiven-service-user-secret
       key: SERVICEUSER_PASSWORD
```

but I think this would make the k8s manifest less verbose and simpler for the end-user.
